# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Storable
version:      0.01
version_from: Storable.pm
installdirs:  site
requires:
    Class::DBI:                    0
    Storable:                      2.14
    Test::More:                    0
    Test::Warn:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
